# Generated by Django 2.2.5 on 2019-09-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_username', models.TextField()),
                ('category_yesterday', models.TextField()),
                ('category_today', models.TextField()),
                ('category_bad', models.TextField()),
                ('category_other', models.TextField()),
                ('yesterday', models.TextField()),
                ('today', models.TextField()),
                ('bad', models.TextField()),
                ('other', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
