# Generated by Django 2.2.5 on 2019-11-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='tasktype',
            field=models.TextField(),
        ),
    ]
