# Generated by Django 2.2.7 on 2019-11-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_username', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('teiji', models.TextField(null=True)),
                ('ontime', models.TextField(null=True)),
                ('Date', models.DateField(null=True)),
                ('Month', models.CharField(max_length=100, null=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
