# Generated by Django 2.2.7 on 2019-11-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0002_btrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btrip',
            old_name='ontime',
            new_name='B_money',
        ),
        migrations.RenameField(
            model_name='btrip',
            old_name='teiji',
            new_name='gout',
        ),
    ]
