# Generated by Django 2.2.7 on 2019-11-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0003_auto_20191122_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kintai',
            old_name='ontime',
            new_name='overtime',
        ),
        migrations.AlterField(
            model_name='kintai',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
