# Generated by Django 2.2.5 on 2019-10-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0003_taskproject_tasktype_taskuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
