# Generated by Django 2.2.5 on 2019-11-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0003_taskmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmessage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
