# Generated by Django 2.2.5 on 2019-10-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_username', models.TextField()),
                ('taskProject', models.TextField()),
                ('tasktype', models.TextField()),
                ('task', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
