# Generated by Django 2.2.7 on 2019-11-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0005_auto_20191115_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmessage',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
