# Generated by Django 2.2.5 on 2019-10-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0005_tasktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
