# Generated by Django 2.2.7 on 2019-11-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0005_kintai_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='kintai',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
