# Generated by Django 2.2.5 on 2019-10-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0006_auto_20191031_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
