# Generated by Django 2.2.7 on 2019-11-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0007_remove_kintai_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='btrip',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
