# Generated by Django 2.2.7 on 2019-11-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0008_btrip_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btrip',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
