# Generated by Django 2.2.7 on 2019-11-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0010_btrip_kakunin'),
    ]

    operations = [
        migrations.AddField(
            model_name='kintai',
            name='kakunin',
            field=models.BooleanField(default=False),
        ),
    ]
