# Generated by Django 2.2.7 on 2019-11-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0011_kintai_kakunin'),
    ]

    operations = [
        migrations.AddField(
            model_name='btrip',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kintai',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
