# Generated by Django 2.2.7 on 2019-12-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0012_auto_20191129_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='btrip',
            name='created_month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kintai',
            name='created_month',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
