# Generated by Django 2.2.7 on 2019-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0013_auto_20191202_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btrip',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kintai',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
