# Generated by Django 2.2.7 on 2019-12-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0015_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
