# Generated by Django 2.2.7 on 2019-12-17 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0016_chat_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
