# Generated by Django 2.2.7 on 2019-12-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useractivities', '0018_jinkenhi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jinkenhi',
            name='username',
        ),
    ]
